### ISSUE TITLE
TENARIS - Solicitar nuevo usuario para JM

### ISSUE THREAD

**Issue by jmusanti** [brosenburt/TENARIS#2]
Se debe solicitar un nuevo usuario para JM

**Comment by PabloGottig** [comment]
Firmar acuerdo de confidencialidad, escanear y responder el correo

**Comment by PabloGottig** [comment]
Probar el usuario nuevo, pedir los accesos para ese usuario al modelo de ENGI y HSE

**Comment by PabloGottig** [comment]
Pedi los permisos sobre HSE, pedi acceso a un LAB nuevo, y acceso VPN.

Falta pedir los permisos sobre ENGI.
